// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  contact_block: dynamic(() => import("./ContactBlock")),
  content_index: dynamic(() => import("./ContentIndex")),
  experience_slice: dynamic(() => import("./ExperienceSlice")),
  hero: dynamic(() => import("./Hero")),
  image_block: dynamic(() => import("./ImageBlock")),
  techlist: dynamic(() => import("./Techlist")),
  textblock: dynamic(() => import("./Textblock")),
};
